### ISSUE TITLE
Arrays in verifyProof() function are set to calldata

### ISSUE THREAD

**Issue by todesstille** [dl-solarity/hardhat-zkit#10]
### Describe the feature

When generating verifier contract, proof variables type is set to "calldata". It is not very convenient when you try to inherit verifier.sol, instead of using it as standalone contract, because public parts of a proof could be constructed during the transaction execution in the memory.

It would be nice to have memory type as default or some option to choose between both types.

**Comment by Arvolear** [comment]
Thanks! Will include that in our features list.
