### ISSUE TITLE
Error HH902: Variable importName's tag not present in the template 

### ISSUE THREAD

**Issue by Brianspha** [dl-solarity/hardhat-zkit#27]
Hello,

I seem to be facing an issue when trying to test a circuit I'm getting the below error:

Error HH902: Variable importName's tag not present in the template For more info go to https://hardhat.org/HH902 or run Hardhat with --show-stack-traces.

```
import { zkit } from "hardhat"; // hardhat-zkit plugin
import { expect } from "chai"; // chai-zkit extension
import { SomeCircuit } from "@zkit"; // zktype circuit-object
async function main() {
  const circuit: SomeCircuit = await zkit.getCircuit("SomeCircuit");
  await expect(circuit)
    .with.witnessInputs({ a: "4", b: "2" })
    .to.have.witnessOutputs({ c: "2" });
  const proof = await circuit.generateProof({ a: "4", b: "2" });
  expect(await circuit.verifyProof(proof)).to.be.true;
}

main()
  .then()
  .catch((e) => console.log(e));

```

**Comment by Arvolear** [comment]
Hey @Brianspha, thanks for reporting this! We have fixed this bug (the errors are now displayed properly) in the upcoming version `0.4.0`.

Will close this issue once the update is ready.

**Comment by Brianspha** [comment]
@Arvolear awesome
