### ISSUE TITLE
Error: Cannot find module '@src/cache/BaseCache'

### ISSUE THREAD

**Issue by frankhillard** [dl-solarity/hardhat-zkit#33]
### hardhat-zkit version

0.4.3

### What happened?

I follow the documentation and add the `import "@solarity/hardhat-zkit";` in the hardhat.config.ts file. I run `npx hardhat help`. It crashes with missing module.  For example in file CircuitsCompileCache.d.ts there is  `import { BaseCache } from "@src/cache/BaseCache";` . Shouldn't be replace by `import { BaseCache } from "../cache/BaseCache";`.

### Minimal reproduction steps

- add the `import "@solarity/hardhat-zkit";` in the hardhat.config.ts file
- run `npx hardhat help`.

**Comment by frankhillard** [comment]
Setup project:
- `mkdir testdir`
- `cd testdir`
- `pnpm init`
- `pnpm add -D hardhat`
- `npx hardhat init`
Once project created, go to hardhat.config.ts and add `import "@solarity/hardhat-zkit";`
- `npx hardhat help`

**Comment by Arvolear** [comment]
Hey @frankhillard, thanks for reporting this. This should be fixed now in the plugin version `0.4.4`, please try it out.
