### ISSUE TITLE
Frontend parsing failure

### ISSUE THREAD

**Issue by 1KitCat1** [dl-solarity/hardhat-zkit#40]
### hardhat-zkit version

0.4.6

### What happened?

```
 var HASH_BLOCK_SIZE = 1024;
    if (HASH_TYPE <= 256){
        HASH_BLOCK_SIZE = 512;
    }
...
72:    signal input encapsulatedContent[EC_BLOCK_NUMBER * HASH_BLOCK_SIZE];
```

Using hardhat-zkit an error occured:
```
    at Array.forEach (<anonymous>) {
  errors: [
    {
      message: 'Unresolvable identifier HASH_BLOCK_SIZE',
      line: 72,
      column: 55
    }
  ]
}
Error during hardhat zkit compile
```
Is it correctly compiled using native compiler.

### Minimal reproduction steps

-

**Comment by Arvolear** [comment]
Minimal viable support for `var` variables has been added to the plugin `v0.4.8`. The given example should now work.
